version: '3.8'

services:
  user-service:
    build: ./user-service
    volumes:
      - user-db-data:/app/db
      - ./user-service/migrations:/app/migrations
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - USER_DB_PATH=${USER_DB_PATH}
      - JWT_ACCESS_EXP_MINUTES=${JWT_ACCESS_EXP_MINUTES}
      - JWT_REFRESH_EXP_DAYS=${JWT_REFRESH_EXP_DAYS}
      - HARDCODED_ADMIN_USERNAME=${HARDCODED_ADMIN_USERNAME}
      - HARDCODED_ADMIN_PASSWORD=${HARDCODED_ADMIN_PASSWORD}
    ports:
      - "5003:5000"
    networks:
      - app-network

  product-service:
    build: ./product-service
    volumes:
      - product-db-data:/app/db
    environment:
      - PRODUCT_DB_PATH=${PRODUCT_DB_PATH}
      - USER_SERVICE_URL=http://nginx:80
    depends_on:
      - user-service
    ports:
      - "5001:5001"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - user-service
      - product-service
    networks:
      - app-network

volumes:
  user-db-data:
  product-db-data:

networks:
  app-network:
    driver: bridge